name: iteach
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  file_picker: ^8.1.7
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  get: ^4.6.6
  get_it: ^8.0.3
  get_storage: ^2.1.1
  http: ^1.3.0
  http_interceptor: ^2.0.0
  internet_connection_checker: ^1.0.0

  intl: ^0.20.1
  logger: ^2.5.0
  path: ^1.9.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/

  uses-material-design: true
